version: "3"
services:
  jupyter:
    image: gcr.io/kaggle-images/python:v68
    volumes:
      - $PWD:/tmp/working
    working_dir: /tmp/working
    ports:
      - 8888:8888
    command: jupyter notebook --ip=0.0.0.0 --allow-root --no-browser